apiVersion: apps/vlbetal
kind: Deployment 
metadata:
 name: mhc-back
spec: 
 replicas: 1
 template: 
  metadata: 
   labels: 
     app: mhc-back 
  spec: 
   containers: 
   -name: mhc-back
    image: redis
   ports: 
    -containerPort: 6379
   name: redis
   
---
apiVersion: v1
kind: Service
metadata:
 name: mhc-back 
spec: 
 ports: 
 -port: 6379
  selector: 
   app: mhc-back 
   
--- 
apiVersion: apps/vlbetal
kind: Deployment 
metadata:
 name: mhc-front
spec: 
 replicas: 1
 strategy: 
 rollingUpdate: 
  maxSurge: 1
  maxUnavailable: 1
minReadySeconds: 5
 template: 
  Metadata: 
  labels: 
   app: mhc-front
  spec: 
   containers: 
   -name: mhc-front
   image: akshandsonlabacr.azurecr
   imagePullPolicy: Always
   ports: 
    -container port: 80
   resources: 
    requests: 
      cpu: 250m 
   limits: 
      cpu: 500m
  env:
  -name: Redis
    value: "mhc-back"
    
---
apiVersion: V1
kind: Service
metadata: 
 name: mhc-front
spec: 
 type: LoadBalancer
 ports: 
 -ports: 80 
 Selector: 
  app: mhc-front
